image: golang:latest

#services:
#  - name: postgres:latest

variables:
  # Please edit to your GitLab project
  REPO_NAME: gitlab.com/ntsft/tsvc/prework/rain-end

before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME

stages:
  - static
  - build
  - deploy

check:
  stage: static
  #allow_failure: true
  script:
    #- go fmt $(go list ./... | grep -v /vendor/)
    #- go vet $(go list ./... | grep -v /vendor/)
    - go static -v -count=1 static/tests #$(go list ./... | grep -v /vendor/)
    - go static -v -count=1 static/tests -static.bench=. -run=none

compile:
  stage: build
  script:
    - go build -race -ldflags "-extldflags '-static'" -o $CI_PROJECT_DIR/binary
  artifacts:
    name: "$CI_PIPELINE_ID"
    expire_in: 1 week
    paths:
      - binary
