image: golang:latest

#services:
#  - name: postgres:latest

variables:
  REPO_NAME: gitlab.com/ntsft/tsvc/prework/rain-end

before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME

stages:
  - test
  - build
  - deploy

check:
  stage: test
  #allow_failure: true
  script:
    #- go fmt $(go list ./... | grep -v /vendor/)
    #- go vet $(go list ./... | grep -v /vendor/)
    - go test -v -count=1 test/tests #$(go list ./... | grep -v /vendor/)
    - go test -v -count=1 test/tests -test.bench=. -run=none

compile:
  stage: build
  script:
    - docker run -v "$GOPATH":/go --rm -v "$PWD":/app -w /app -e GOOS="linux" -e GOARCH="amd64" -e GOPROXY="https://goproxy.cn,https://goproxy.io,direct" golang:latest go build -v
