[DB]
#replace with your own db dns
#postgres-app / localhost / IP
conn = "host=postgres-app user=postgres password=sasa dbname=postgres port=5432"
#print raw sql
debug = false

[Server]
#ip:port
addr = ":9090"
#print request log
debug = true

useTLS = false
cert = "tls/server.crt"
key = "tls/server.key"