version: '3'
services:
  postgres:
    image: library/postgres:latest
    container_name: postgres-app
    ports:
    - 5432:5432

    environment:
      - POSTGRES_PASSWORD=sasa


  test:
    build: .
    image: msg-test:latest
    container_name: msg-test-app
    command: ./wait-for-it.sh localhost:5432
    ports:
      - 9090:9090
    depends_on:
      - postgres
