version: '3'
services:
  postgres:
    image: library/postgres:latest
    container_name: postgres-app
    networks:
      - msg-test-network

    environment:
      - POSTGRES_PASSWORD=sasa


  test:
    build: .
    image: msg-test:latest
    container_name: msg-test-app
    ports:
      - 9090:9090
    networks:
      - msg-test-network
    depends_on:
      - postgres


networks:
  msg-test-network:
